version: '1'

services:
  db:
    image: postgres:latest
    container_name: 'discord_clone-db'
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=postgresadmin123
      - POSTGRES_DB=discord_clone
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d

volumes:
  postgres_data: