export const JWT_AT_STRATEGY_NAME = 'JWT_AT_STRATEGY';
export const JWT_AT_AUTHORIZE_STRATEGY_NAME = 'JWT_AT_AUTHORIZE_STRATEGY';
export const JWT_VT_STRATEGY_NAME = 'JWT_VT_STRATEGY';
export const JWT_RT_STRATEGY_NAME = 'JWT_RT_STRATEGY';
